import type { AidipServices } from './rayfin/aidip';
import { IAuthService } from './interfaces/IAuthService';
import { RayfinAuthService } from './rayfin/RayfinAuthService';
import { RayfinClientService } from './rayfin/RayfinClientService';
import { createRayfinAidipServices } from './rayfin/aidip';

/**
 * Service container — manages all application services.
 *
 * Authentication is Rayfin-backed (preserved from the original scaffold —
 * the authentication system is already functional per CDC §4). AIDIP
 * domain services are also Rayfin-backed, querying the live Fabric SQL
 * database through the typed `client.data.<Entity>` accessors.
 *
 * The container requires `VITE_RAYFIN_PUBLISHABLE_KEY` (and the other
 * Rayfin env tokens generated by `rayfin env --framework vite`). If the
 * env is missing, `create()` throws a clear error explaining how to
 * provision it.
 */
export class ServiceContainer {
  private static instance: ServiceContainer | null = null;

  public readonly authService: IAuthService;
  public readonly aidip: AidipServices;

  private constructor(authService: IAuthService, aidip: AidipServices) {
    this.authService = authService;
    this.aidip = aidip;
  }

  /**
   * Create and initialize the service container.
   *
   * @throws Error if `VITE_RAYFIN_PUBLISHABLE_KEY` is missing.
   */
  static create(): ServiceContainer {
    if (!ServiceContainer.instance) {
      const apiUrl =
        import.meta.env.VITE_RAYFIN_API_URL || 'http://localhost:5168';
      const publishableKey = import.meta.env.VITE_RAYFIN_PUBLISHABLE_KEY;

      if (!publishableKey) {
        throw new Error(
          'VITE_RAYFIN_PUBLISHABLE_KEY is required. Run `rayfin env --framework vite` to generate it from your manifest.json tokens, or set it manually in your .env file.',
        );
      }

      console.info('Initializing Rayfin services with API URL:', apiUrl);

      const projectId = import.meta.env.VITE_FABRIC_ITEM_ID;
      const rayfinClientService = RayfinClientService.getInstance();
      rayfinClientService.initialize(
        apiUrl.endsWith('/') ? apiUrl : `${apiUrl}/`,
        publishableKey,
      );

      const isLocalEnvironment =
        new URL(apiUrl).hostname === 'localhost' ||
        new URL(apiUrl).hostname === '127.0.0.1';

      const workspaceId = import.meta.env.VITE_FABRIC_WORKSPACE_ID;
      const fabricPortalUrl = import.meta.env.VITE_FABRIC_PORTAL_URL;
      const hasFabricConfig = !!(workspaceId && projectId && fabricPortalUrl);

      const authBuilder = RayfinAuthService.builder();
      if (isLocalEnvironment) authBuilder.withUsernameAuth();
      if (hasFabricConfig) {
        authBuilder.withFabricAuth({ workspaceId, projectId, fabricPortalUrl });
      }

      ServiceContainer.instance = new ServiceContainer(
        authBuilder.build(),
        createRayfinAidipServices(),
      );
    }

    return ServiceContainer.instance;
  }

  static getInstance(): ServiceContainer {
    if (!ServiceContainer.instance) {
      throw new Error('ServiceContainer not initialized. Call create() first.');
    }
    return ServiceContainer.instance;
  }

  static reset(): void {
    ServiceContainer.instance = null;
    RayfinClientService.reset();
  }
}
