/**
 * AUTO-GENERATED by `rayfin functions typegen`.
 *
 * Do not edit this file manually — it is overwritten by the typegen
 * watcher on every save of `function_app.ts`.
 *
 * Run `npx rayfin functions typegen` (or `--watch`) to regenerate.
 *
 * The schema below mirrors the `udf.func(name, handler, [])` calls in
 * `function_app.ts`. It is consumed by `RayfinClient<AidipSchema, AppFunctionsSchema>`
 * in the front-end so that `client.functions.<name>.invoke(args)` is
 * fully type-checked.
 */

export type AppFunctionsSchema = {
  chat: {
    input: {
      conversationId: string;
      text: string;
    };
    output: {
      text: string;
      sourceCitation?: string;
      visualization?: {
        type: 'line' | 'bar' | 'pie' | 'area' | 'kpi';
        title: string;
        source: string;
        series: { label: string; value: number }[];
        xAxisLabel?: string;
        yAxisLabel?: string;
      };
      table?: {
        columns: { key: string; label: string; format?: 'currency' | 'percent' | 'integer' | 'date' | 'text' }[];
        rows: Record<string, string | number>[];
        totalRows: number;
      };
      insights?: { kind: 'trend' | 'anomaly' | 'recommendation'; text: string }[];
      daxQuery?: string;
      tokensUsed?: number;
      modelUsed?: string;
      responseTimeMs?: number;
      errorKind?: 'ai_unavailable' | 'fabric_unavailable' | 'timeout' | 'quota_exceeded' | 'empty_data';
    };
  };

  exportReport: {
    input: {
      snapshotId: string;
      reportId: string;
      config: {
        format: 'pdf' | 'ppt';
        includeCoverPage?: boolean;
        includeTableOfContents?: boolean;
        includeCompanyLogo?: boolean;
        quality?: 'standard' | 'high';
        sectionRange?: { from: number; to: number } | null;
        pptTemplate?: 'standard' | 'minimal';
        includeDataTables?: boolean;
      };
    };
    output: {
      ok: boolean;
      fileUrl?: string;
      fileSizeKb?: number;
      errorMessage?: string;
    };
  };

  getKpiValues: {
    input: { kpiIds: string[] };
    output: Record<
      string,
      {
        value: number;
        comparison?: { value: number; label: string };
        sparkline?: number[];
      }
    >;
  };

  startImpersonation: {
    input: { targetUserId: string; reason: string };
    output: {
      ok: boolean;
      message?: string;
      session?: {
        superAdminId: string;
        superAdminName: string;
        targetUserId: string;
        targetUserEmail: string;
        targetUserName: string;
        targetCompanyName: string;
        reason: string;
        startedAt: string;
      };
      /** Short-lived impersonation JWT (HMAC-SHA256 signed with Invitation__Secret).
       * The client stores it and includes it in subsequent requests so the
       * server can identify the active impersonation session. */
      token?: string;
      /** ISO-8601 expiry timestamp (now + 30 min). */
      expiresAt?: string;
    };
  };

  endImpersonation: {
    input: void;
    output: { ok: boolean };
  };

  getImpersonationState: {
    input: void;
    output: {
      active: boolean;
      session?: {
        superAdminId: string;
        superAdminName: string;
        targetUserId: string;
        targetUserEmail: string;
        targetUserName: string;
        targetCompanyName: string;
        reason: string;
        startedAt: string;
      };
    };
  };

  testFabricConnection: {
    input: { companyId: string };
    output: { ok: boolean; message: string; xmlaLatencyMs?: number };
  };

  extractSemanticSchema: {
    input: { companyId: string };
    output: {
      ok: boolean;
      tablesFound: number;
      tables?: Array<{ name: string; columns: string[]; measures: string[] }>;
      message?: string;
    };
  };

  generateAiInsight: {
    input: {
      prompt: string;
      length: 'short' | 'medium' | 'long';
      previousSectionData?: {
        type: 'chart' | 'table' | 'kpi' | 'text';
        title?: string;
        series?: { label: string; value: number }[];
        rows?: Record<string, string | number>[];
        kpiValue?: number;
        kpiLabel?: string;
        text?: string;
      } | null;
      companyId: string;
    };
    output: {
      ok: boolean;
      bullets: string[];
      tokensUsed?: number;
      modelUsed?: string;
      errorMessage?: string;
    };
  };

  getChatSuggestions: {
    input: { companyId: string; userId: string };
    output: {
      ok: boolean;
      suggestions: string[];
      errorMessage?: string;
    };
  };

  sendInvitationEmail: {
    input: { invitationId: string };
    output: {
      ok: boolean;
      messageId?: string;
      errorMessage?: string;
    };
  };

  sendNotificationEmail: {
    input: { notificationId: string };
    output: {
      ok: boolean;
      messageId?: string;
      errorMessage?: string;
    };
  };

  sendExportReadyEmail: {
    input: { snapshotId: string };
    output: {
      ok: boolean;
      messageId?: string;
      errorMessage?: string;
    };
  };
};
